version: 2

models:
  - name: customer_stream_active_on_subscription
    description: "Activity data triggered when a customer is active on a subscription"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

