version: 2

models:
  - name: ga_cube_churned_revenue
    description: "Flattened OLAP cube model for ChurnedMRR"
    columns:
      - name: metric_date
        description: "The primary key for this table"
        tests:
          - not_null
