version: 2

models:
  - name: ga_cube_churned_revenue
    description: "Flattened OLAP cube model for ChurneddMRR"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
