version: 2

models:
  - name: churned_revenue_cube
    description: "Flattened OLAP cube model for ChurnedMRR"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
