version: 2

models:
  - name: ga_cube_committed_revenue
    description: "Flattened OLAP cube model for CommittedMRR"
    columns:
      - name: anchor_date
        description: "The primary key for this table"
        tests:
          - not_null


