version: 2

models:
  - name: committed_revenue_cube
    description: "Flattened OLAP cube model for CommittedMRR"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


